checkpoint_path: outputs/final_outputs/table_env/transformer_8_8_data_5000_drand.pth
normalization_stats_path: outputs/final_outputs/table_env/transformer_8_8_data_5000_drand.yaml
padding_strategy: zero
