# checkpoint_path: outputs/final_outputs/8To16.pth
# normalization_stats_path: outputs/final_outputs/7DoF.yaml
checkpoint_path: outputs/final_outputs/transformer.pth
normalization_stats_path: outputs/final_outputs/transformer.yaml
padding_strategy: zero
