checkpoint_path: outputs/final_outputs/table_env/tableenv_3d_static_dino_domain_rand.pth
normalization_stats_path: outputs/final_outputs/table_env/tableenv_3d_static_dino_domain_rand.yaml
padding_strategy: zero
