# Base policy configuration
type: multimodal
action_dim: 3
dropout_rate: 0.2        # Still used by obs_encoder (PointNet), which is good!
policy_head_type: diffusion

# Multimodal policy specific settings
state_dim: 7
fusion_method: concat

time_encoding: none
max_timesteps: 64 # This might still be needed if your dataset processing uses it.
observation_mode: depth

# Diffusion Head settings
prediction_length: 8       # length of the generated action trajectory.
num_diffusion_iters: 100    #  Number of denoising steps. Controls the trade-off between sample quality and inference speed.
down_dims: [128, 256, 512] #[256, 512, 1024]