type: multimodal         # Options: pointcloud, multimodal, ensemble

action_dim: 3            # Dimension of action space (SE3 9D representation)
mlp_hidden_dims: [256, 256, 128] # Hidden dimensions for policy MLP head
dropout_rate: 0.2        # Dropout rate for regularization
use_residual: true      # Whether to use residual connections in MLP
output_activation: null  # Output activation function (null for linear output)
policy_head_type: mlp

state_dim: 3            # Same as action_dim for now (maybe change/omit)
# fusion_method: concat  # Method to fuse modalities (concat, add) 

time_encoding: positional
max_timesteps: 64
observation_mode: ${observation_mode}  # inherit from global config