# Base policy configuration
type: multimodal         # Options: pointcloud, multimodal

action_dim: 4            # Dimension of action space 
dropout_rate: 0.2        # Dropout rate for regularization
output_activation: null  
policy_head_type: transformer

# Multimodal policy specific settings
state_dim: 4           # Same as action_dim for now (maybe change/omit)
fusion_method: concat  # Method to fuse modalities (concat, add, concat_project) 

time_encoding: positional

max_timesteps: 64
observation_mode: ${observation_mode}  # inherit from global config

# Transformer settings
context_length: ${context_length} 
prediction_length: ${prediction_length}
embed_dim: 64
num_layers: 2
num_heads: 4
