defaults:
  - _self_  
  - model: mlp_depth
  - loss: default_3d
  - optimizer: adam
  - data: mlp_depth
  - inference: mlp_depth
train:
  batch_size: 32
  epochs: 100
  device: cuda

# Global settings
observation_mode: 'depth'  
seed: 42
experiment_name: "SimpleSingleStepBC"
output_dir: ${hydra:runtime.output_dir}

wandb:
  enabled: false