defaults:
  - _self_  
  - model: transformer_depth
  - loss: default_9d
  - optimizer: adam
  - data: depth
  - trainer: steps
  - scheduler: cosine_warmup
train:
  batch_size: 128
  num_workers: 8
  device: cuda
  grad_clip: 1.0

# Global settings
observation_mode: 'depth'  
seed: 42
experiment_name: "SimpleSingleStepBC"
output_dir: ${hydra:runtime.output_dir}

is_regression: false
# whether to use a separate network for waypoint and timing prediction naming
is_waypointPlusTimings: false

wandb:
  enabled: true