defaults:
  - _self_  
  - model: multi_modal
  - loss: default_3d
  - optimizer: adam
  - data: single_step
  - inference: default
train:
  batch_size: 32
  epochs: 100
  device: cuda

# Global settings
seed: 42
experiment_name: "SimpleSingleStepBC"
output_dir: ${hydra:runtime.output_dir}

