# configs/data_collection.yaml
# TODO
robot_mode: "floating"         # "normal" or "floating"
collect_data: true
path_mode: "SE39D"             # "JOINT7D", "SE38D", or "SE39D"
simulate: true
camera_name: "cameraStatic"    # or "cameraWrist"

shelf_pos_xyz: [0.7, 0.05, 0.25]
shelf_quaternion: [1, 0, 0, 1]
shelf_openings_small: [4, 11]
shelf_equidistant: false

num_samples_books: 10
num_boxes_per_sample: 1
allow_book_yaw: false

box_size_ranges:
  x: [0.07, 0.1]
  y: [0.1, 0.15]
  z: [0.01, 0.025]

h5_filename: "my_shelf_pull_data.h5"

hydra:
  run:
    dir: .
  output_subdir: null

  job:
    logging:
      level: CRITICAL  # Reduce noise from Hydra itself (optional)

  # Disable hydra's file logging
  verbose: false
  output_subdir: null
  logging:
    config: null
