defaults:
  - _self_  
  - model: regression
  - data: depth
  - inference: sam_regression
  - env: table_3d_abs_push

experiment_name: "Transformer 10 step input Inference"
observation_mode: sam_points
output_subdir: null
num_eval_episodes: 50
simulate: True
is_waypointPlusTimings: False
seed: 42
is_regression: true


hydra:
  run:
    dir: ./eval_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}