defaults:
  - _self_  
  - model: transformer_depth
  - data: depth
  - inference: transformer_depth_table
  - env: table_3d_abs_push

experiment_name: "Transformer 10 step input Inference"
observation_mode: dino_cls
output_subdir: null
num_eval_episodes: 500
simulate: True
is_waypointPlusTimings: False
action_execution_horizon: 16
seed: 42
context_length: 8
prediction_length: 16

hydra:
  run:
    dir: ./eval_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}