defaults:
  - _self_  
  - model: recurrent_depth
  - data: depth
  - inference: gru_depth
  - env: default_3d

experiment_name: "SimpleSingleStepBC Inference"
observation_mode: 'depth'
output_subdir: null
