defaults:
  - _self_  
  - model: diffusion_depth
  - data: depth
  - inference: diffusion_depth
  - env: default_3d

experiment_name: "Transformer 10 step input Inference"
observation_mode: 'depth'
output_subdir: null
num_eval_episodes: 500
simulate: True
is_waypointPlusTimings: False
action_execution_horizon: 5
seed: 42

hydra:
  run:
    dir: ./eval_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}