defaults:
  - _self_  
  - model: transformer_depth_wayptime
  - data: depth
  - inference: transformer_depth
  - env: default_3d

experiment_name: "Transformer 10 step input Inference"
observation_mode: 'depth'
output_subdir: null
num_eval_episodes: 100
simulate: True
is_waypointPlusTimings: False