defaults:
  - _self_  
  - model: transformer_depth
  - data: depth
  - inference: transformer_depth_shelf
  - env: shelf_hook_floating

experiment_name: "Transformer 10 step input Inference"
observation_mode: depth
output_subdir: null
num_eval_episodes: 20
simulate: True
is_waypointPlusTimings: False
action_execution_horizon: 8
seed: 42
context_length: 8
prediction_length: 8

hydra:
  run:
    dir: ./eval_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}