path_mode: jointspace
robot_mode: normal         # "normal" or "floating"
end_effector: hook        # "hook" or null
simulate: true
botop: false
on_real: false
camera_name: cameraShelf    # or "cameraWrist"
env: ShelfEnv-v1

task: hook
obj: book

allow_book_yaw: false
q0: [-0.11823945, -0.27751445, 0.54293547, -1.74915798, -1.21386092, 1.0878208,-0.70455155] #[ 0., -0.5, 0., -2., 0., 2., -0.5]

# .98
shelf_pos_xyz: [.98, 0.14, .206]
shelf_quaternion: [1, 0, 0, 1]
shelf_floor_offsets: [0.35, 0.43, 0.38, 0.18, 0.15, 0.2, 0.15, 0.15, 0.15, 0.12]  # Last 2 entries TODO

rotate_panda_base: false

margins:
  x_min: 0.05
  x_max: 0.05
  y_min: 0.05
  y_max: 0.05


box_size_ranges:
  x: [0.1, 0.15]
  y: [0.14, 0.23]
  z: [0.035, 0.045]

hook_base_length: 0.4
hook_tip_length: 0.14
hook_width: 0.025

# camera_offset_ranges:
#   x: [-0.1, 0.1]
#   y: [-0.1, 0.1]
#   z: [-0.1, 0.1]

# camera_rpy_ranges:
#   roll: [-5, 5]
#   pitch: [-10, 10]
#   yaw: [-15, 15]


focal_length_range: [0.895, 0.895]
