path_mode: jointspace
robot_mode: normal         # "normal" or "floating"
end_effector: hook        # "hook" or null
simulate: true
botop: false
on_real: false
camera_name: cameraShelf    # or "cameraWrist"
env: ShelfEnv-v1

task: hook
obj: book

allow_book_yaw: false
q0: [ 0.,  -1,  0.,  -2.,   0.,   2.,  -2.4]

shelf_pos_xyz: [.9, -0.1, .3]
shelf_quaternion: [1, 0, 0, 1]
shelf_floor_offsets: [0.35, 0.43, 0.50, 0.18, 0.15, 0.2, 0.15, 0.15, 0.15, 0.12]  # Last 2 entries TODO

box_size_ranges:
  x: [0.1, 0.15]
  y: [0.14, 0.23]
  z: [0.009, 0.045]

# camera_offset_ranges:
#   x: [-0.1, 0.1]
#   y: [-0.1, 0.1]
#   z: [-0.1, 0.1]

# camera_rpy_ranges:
#   roll: [-5, 5]
#   pitch: [-10, 10]
#   yaw: [-15, 15]


focal_length_range: [0.895, 0.895]
