
robot_mode: pos3d         # "normal" or "floating"
simulate: true
botop: false
on_real: false
camera_name: cameraStatic    # or "cameraWrist"
env: table

allow_book_yaw: false

# TODO use ranges and box positions
box_size_ranges:
  x: [0.1, 0.15]
  y: [0.14, 0.23]
  z: [0.009, 0.045]

table_offset_ranges:
  width: [-0.25, 0.25]
  length: [-0, 0.1]
  yaw: [-24., -16.]

camera_offset_ranges:
  x: [0.0, 0.0]
  y: [0, 0.]
  z: [0, 0.]

camera_rpy_ranges:
  roll: [-5, 5]
  pitch: [-10, 10]
  yaw: [-15, 15]

depth_noise_ranges:
  active: True
  binocular_baseline: [0.0, .1]
  depth_smoothing: [1, 1]
  noise_all: [0.0, .2]
  noise_wide: [0., 0.2]
  noise_local: [0., 0.1]
  noise_pixel: [0.0, 0.01]

focal_length_range: [0.895, 0.895]
