
robot_mode: normal         # "normal" or "floating"
path_mode: taskspace

simulate: false
botop: true
on_real: true
camera_name: cameraWrist    # or "cameraWrist"
env: TableEnv-v0
q0: [0.02460767, 0.28028935, -0.03155226, -1.1576008,  -0.01385739,  1.4093496, 0.76464119]
task: push
obj: cylinder

box_size_ranges:
  x: [0.05905, 0.0605]
  y: [0.05905, 0.0605]
  z: [0.05905, 0.0605]


box_offset_ranges:
  x: [-0.05, 0.25]
  y: [-0.2, 0.0] 

table_offset_ranges:
  width: [0.0, 0.0]
  length: [0.0, 0.0]
  yaw: [0, 0]

camera_offset_ranges:
  null

camera_rpy_ranges:
  null

focal_length_range: null

depth_noise_ranges: null

