
robot_mode: normal         # "normal" or "floating"
path_mode: pos3d_rel

simulate: true
botop: false
on_real: false
camera_name: cameraWrist    # or "cameraWrist"
env: TableEnv-v0

task: push
obj: cylinder

box_size_ranges:
  x: [0.05905, 0.0605]
  y: [0.05905, 0.0605]
  z: [0.05905, 0.0605]


box_offset_ranges:
  x: [-0.05, 0.25]
  y: [-0.2, 0.0] 

table_offset_ranges:
  width: [0.0, 0.0]
  length: [0.0, 0.0]
  yaw: [0, 0]

camera_offset_ranges:
  null

camera_rpy_ranges:
  null

focal_length_range: null

depth_noise_ranges: null

